kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "PYTHONPATH=../.. uv run uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[services.production]
[services.production.run]
args = ["uv", "run", "uvicorn", "backend.main:app", "--app-dir", ".", "--host", "0.0.0.0", "--port", "8080"]

[services.production.run.env]
PORT = "8080"
PYTHONPATH = "."

[services.production.health.startup]
path = "/api/healthz"
